[general]
cpus = 16
editor = "nano"
doas = false
language = "en-US"
noconfirm = false

[aur]
build = "$HOME/.cache/aura/builds"
cache = "$HOME/.cache/aura/cache"
clones = "$HOME/.cache/aura/packages"
hashes = "$HOME/.cache/aura/hashes"
chroot = []
ignores = []
git = false
hotedit = false
shellcheck = false
diff = false
delmakedeps = true
clean = false
warn_unknowns = true
nocheck = false
skipdepcheck = false
reverse = false

[backups]
snapshots = "$HOME/.cache/aura/snapshots"
automatic = true

